name: Workflow 2
on:
  workflow_dispatch:

jobs:
  run-fetch-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install pytz

    - name: Run script
      run: python fetch_data.py
      env:
        FB_ACCESS_TOKEN: ${{ secrets.FB_ACCESS_TOKEN }} 
        URL: ${{ secrets.URL }} 
        ONE: ${{ secrets.ONE }} 
        THREE: ${{ secrets.THREE }} 

    - name: Send data
      run: python send.py
      env:
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}  

    - name: Trigger Workflow 1
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
        -H "Accept: application/vnd.github.v3+json" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/run1.yml/dispatches \
        -d '{"ref":"main"}'
